logging:
  level:
    root: INFO

server:
  port: 8080

spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:h2:mem:aws_sns_test_db;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath*:schema/create.sql
      encoding: UTF-8
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console