logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

server:
  port: 8060

spring:
  cloud:
    config:
      enabled: false
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
  datasource:
    url: jdbc:h2:mem:aws_sns_test_db;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations: classpath*:schema/create.sql
      encoding: UTF-8
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

aws:
  sqs:
    FIRST_BENEFIT_CREATION_QUEUE: FIRST_BENEFIT_CREATION_QUEUE

endpoint:
  order-v1: http://localhost:8080/v1/orders